# Generated by Django 4.2.2 on 2023-07-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contract',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profiles',
                related_query_name='profile',
                to='core.contract',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profiles',
                related_query_name='profile',
                to='accounts.gender',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profiles',
                related_query_name='profile',
                to='core.level',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profiles',
                related_query_name='profile',
                to='core.salary',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profiles',
                related_query_name='profile',
                to='core.status',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(related_name='profiles', related_query_name='profile', to='core.tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_format',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profiles',
                related_query_name='profile',
                to='core.workformat',
            ),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cities',
                related_query_name='city',
                to='accounts.country',
            ),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='addresses',
                related_query_name='address',
                to='accounts.city',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('city', 'street', 'house_number', 'office_number')},
        ),
    ]
