# Generated by Django 4.2.2 on 2023-06-19 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'Genders'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='languagelevel',
            options={'verbose_name_plural': 'Language levels'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='profilelanguage',
            options={'verbose_name_plural': 'Profile languages'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name_plural': 'Salaries'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='workformat',
            options={'verbose_name_plural': 'Work formats'},
        ),
    ]
