# Generated by Django 4.2.2 on 2023-07-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_alter_response_status_alter_salary_max_salary_and_more'),
        ('accounts', '0003_populate_tables_with_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='profiles',
                related_query_name='profile',
                to='core.status',
            ),
        ),
    ]
