# Generated by Django 4.2.2 on 2023-07-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_alter_adress_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='office_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
