# Generated by Django 4.2.2 on 2023-06-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employees_number',
            options={'verbose_name_plural': 'Employees numbers'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name_plural': 'Responses'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name_plural': 'Reviews ratings'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name_plural': 'Social links'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='web_site',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
