# Generated by Django 4.2.2 on 2023-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_tag_profile_tags'),
        ('core', '0002_alter_adress_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='companies',
        ),
        migrations.AddField(
            model_name='company',
            name='sectors',
            field=models.ManyToManyField(
                related_name='companies_sectors', to='core.sector'
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(
                related_name='employees_positions', to='core.position'
            ),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(
                related_name='vacancies_tags', to='accounts.tag'
            ),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
