# Generated by Django 4.2.2 on 2023-07-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_alter_response_status_alter_salary_max_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='web_site',
            field=models.URLField(),
        ),
    ]
