# Generated by Django 4.2.2 on 2023-06-19 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_remove_position_employees_remove_sector_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='years_exp',
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(120)]
            ),
        ),
    ]
