# Generated by Django 4.2.2 on 2023-06-20 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_vacancy_years_exp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees_number',
            new_name='EmployeesNumber',
        ),
    ]
